# SPDX-FileCopyrightText: 2026 Damián Búho <damian.buho@proton.me>
#
# SPDX-License-Identifier: MIT

# Auto-generated by generate-deps.sh — do not edit

$(FETCH_PATH)/.oracle.21.0.12.amd64.stamp: .container/base/deps/java/oracle/amd64.url.deps .container/base/deps/java/oracle/21/version.deps
	M6E_DEPS_STAGE=base M6E_SERIES=21 TARGETARCH=amd64 .makefile/container/scripts/fetch.sh java/oracle
	touch $@

.container/base/deps/java/oracle/21/amd64.hash.deps: $(FETCH_PATH)/.oracle.21.0.12.amd64.stamp
	M6E_DEPS_STAGE=base M6E_SERIES=21 TARGETARCH=amd64 .makefile/container/scripts/update-hash.sh java/oracle

PREREQUISITES += .container/base/deps/java/oracle/21/amd64.hash.deps

$(FETCH_PATH)/.oracle.21.0.12.arm64.stamp: .container/base/deps/java/oracle/arm64.url.deps .container/base/deps/java/oracle/21/version.deps
	M6E_DEPS_STAGE=base M6E_SERIES=21 TARGETARCH=arm64 .makefile/container/scripts/fetch.sh java/oracle
	touch $@

.container/base/deps/java/oracle/21/arm64.hash.deps: $(FETCH_PATH)/.oracle.21.0.12.arm64.stamp
	M6E_DEPS_STAGE=base M6E_SERIES=21 TARGETARCH=arm64 .makefile/container/scripts/update-hash.sh java/oracle

PREREQUISITES += .container/base/deps/java/oracle/21/arm64.hash.deps

$(FETCH_PATH)/.oracle.25.0.4.amd64.stamp: .container/base/deps/java/oracle/amd64.url.deps .container/base/deps/java/oracle/25/version.deps
	M6E_DEPS_STAGE=base M6E_SERIES=25 TARGETARCH=amd64 .makefile/container/scripts/fetch.sh java/oracle
	touch $@

.container/base/deps/java/oracle/25/amd64.hash.deps: $(FETCH_PATH)/.oracle.25.0.4.amd64.stamp
	M6E_DEPS_STAGE=base M6E_SERIES=25 TARGETARCH=amd64 .makefile/container/scripts/update-hash.sh java/oracle

PREREQUISITES += .container/base/deps/java/oracle/25/amd64.hash.deps

$(FETCH_PATH)/.oracle.25.0.4.arm64.stamp: .container/base/deps/java/oracle/arm64.url.deps .container/base/deps/java/oracle/25/version.deps
	M6E_DEPS_STAGE=base M6E_SERIES=25 TARGETARCH=arm64 .makefile/container/scripts/fetch.sh java/oracle
	touch $@

.container/base/deps/java/oracle/25/arm64.hash.deps: $(FETCH_PATH)/.oracle.25.0.4.arm64.stamp
	M6E_DEPS_STAGE=base M6E_SERIES=25 TARGETARCH=arm64 .makefile/container/scripts/update-hash.sh java/oracle

PREREQUISITES += .container/base/deps/java/oracle/25/arm64.hash.deps

$(FETCH_PATH)/.oracle.26.0.2.amd64.stamp: .container/base/deps/java/oracle/amd64.url.deps .container/base/deps/java/oracle/26/version.deps
	M6E_DEPS_STAGE=base M6E_SERIES=26 TARGETARCH=amd64 .makefile/container/scripts/fetch.sh java/oracle
	touch $@

.container/base/deps/java/oracle/26/amd64.hash.deps: $(FETCH_PATH)/.oracle.26.0.2.amd64.stamp
	M6E_DEPS_STAGE=base M6E_SERIES=26 TARGETARCH=amd64 .makefile/container/scripts/update-hash.sh java/oracle

PREREQUISITES += .container/base/deps/java/oracle/26/amd64.hash.deps

$(FETCH_PATH)/.oracle.26.0.2.arm64.stamp: .container/base/deps/java/oracle/arm64.url.deps .container/base/deps/java/oracle/26/version.deps
	M6E_DEPS_STAGE=base M6E_SERIES=26 TARGETARCH=arm64 .makefile/container/scripts/fetch.sh java/oracle
	touch $@

.container/base/deps/java/oracle/26/arm64.hash.deps: $(FETCH_PATH)/.oracle.26.0.2.arm64.stamp
	M6E_DEPS_STAGE=base M6E_SERIES=26 TARGETARCH=arm64 .makefile/container/scripts/update-hash.sh java/oracle

PREREQUISITES += .container/base/deps/java/oracle/26/arm64.hash.deps

$(FETCH_PATH)/.temurin.21.0.12.amd64.stamp: .container/base/deps/java/temurin/amd64.url.deps .container/base/deps/java/temurin/21/version.deps .container/base/deps/java/temurin/21/build.deps
	M6E_DEPS_STAGE=base M6E_SERIES=21 TARGETARCH=amd64 .makefile/container/scripts/fetch.sh java/temurin
	touch $@

.container/base/deps/java/temurin/21/amd64.hash.deps: $(FETCH_PATH)/.temurin.21.0.12.amd64.stamp
	M6E_DEPS_STAGE=base M6E_SERIES=21 TARGETARCH=amd64 .makefile/container/scripts/update-hash.sh java/temurin

PREREQUISITES += .container/base/deps/java/temurin/21/amd64.hash.deps

$(FETCH_PATH)/.temurin.21.0.12.arm64.stamp: .container/base/deps/java/temurin/arm64.url.deps .container/base/deps/java/temurin/21/version.deps .container/base/deps/java/temurin/21/build.deps
	M6E_DEPS_STAGE=base M6E_SERIES=21 TARGETARCH=arm64 .makefile/container/scripts/fetch.sh java/temurin
	touch $@

.container/base/deps/java/temurin/21/arm64.hash.deps: $(FETCH_PATH)/.temurin.21.0.12.arm64.stamp
	M6E_DEPS_STAGE=base M6E_SERIES=21 TARGETARCH=arm64 .makefile/container/scripts/update-hash.sh java/temurin

PREREQUISITES += .container/base/deps/java/temurin/21/arm64.hash.deps

$(FETCH_PATH)/.temurin.25.0.4.amd64.stamp: .container/base/deps/java/temurin/amd64.url.deps .container/base/deps/java/temurin/25/version.deps .container/base/deps/java/temurin/25/build.deps
	M6E_DEPS_STAGE=base M6E_SERIES=25 TARGETARCH=amd64 .makefile/container/scripts/fetch.sh java/temurin
	touch $@

.container/base/deps/java/temurin/25/amd64.hash.deps: $(FETCH_PATH)/.temurin.25.0.4.amd64.stamp
	M6E_DEPS_STAGE=base M6E_SERIES=25 TARGETARCH=amd64 .makefile/container/scripts/update-hash.sh java/temurin

PREREQUISITES += .container/base/deps/java/temurin/25/amd64.hash.deps

$(FETCH_PATH)/.temurin.25.0.4.arm64.stamp: .container/base/deps/java/temurin/arm64.url.deps .container/base/deps/java/temurin/25/version.deps .container/base/deps/java/temurin/25/build.deps
	M6E_DEPS_STAGE=base M6E_SERIES=25 TARGETARCH=arm64 .makefile/container/scripts/fetch.sh java/temurin
	touch $@

.container/base/deps/java/temurin/25/arm64.hash.deps: $(FETCH_PATH)/.temurin.25.0.4.arm64.stamp
	M6E_DEPS_STAGE=base M6E_SERIES=25 TARGETARCH=arm64 .makefile/container/scripts/update-hash.sh java/temurin

PREREQUISITES += .container/base/deps/java/temurin/25/arm64.hash.deps

$(FETCH_PATH)/.temurin.26.0.2.amd64.stamp: .container/base/deps/java/temurin/amd64.url.deps .container/base/deps/java/temurin/26/version.deps .container/base/deps/java/temurin/26/build.deps
	M6E_DEPS_STAGE=base M6E_SERIES=26 TARGETARCH=amd64 .makefile/container/scripts/fetch.sh java/temurin
	touch $@

.container/base/deps/java/temurin/26/amd64.hash.deps: $(FETCH_PATH)/.temurin.26.0.2.amd64.stamp
	M6E_DEPS_STAGE=base M6E_SERIES=26 TARGETARCH=amd64 .makefile/container/scripts/update-hash.sh java/temurin

PREREQUISITES += .container/base/deps/java/temurin/26/amd64.hash.deps

$(FETCH_PATH)/.temurin.26.0.2.arm64.stamp: .container/base/deps/java/temurin/arm64.url.deps .container/base/deps/java/temurin/26/version.deps .container/base/deps/java/temurin/26/build.deps
	M6E_DEPS_STAGE=base M6E_SERIES=26 TARGETARCH=arm64 .makefile/container/scripts/fetch.sh java/temurin
	touch $@

.container/base/deps/java/temurin/26/arm64.hash.deps: $(FETCH_PATH)/.temurin.26.0.2.arm64.stamp
	M6E_DEPS_STAGE=base M6E_SERIES=26 TARGETARCH=arm64 .makefile/container/scripts/update-hash.sh java/temurin

PREREQUISITES += .container/base/deps/java/temurin/26/arm64.hash.deps

